fixtures:
  symlinks:
    nagios: "#{source_dir}"
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.6.0"
    rsync:
      repo: "puppetlabs/rsync"
      ref: "0.4.0"
    nrpe:
      repo: "pdxcat/nrpe"
      ref: "1.0.0"
    firewall:
      repo: "puppetlabs/firewall"
      ref: "1.5.0"
    xinetd:
      repo: "puppetlabs/xinetd"
      ref: "1.5.0"
    download_file:
      repo: "puppet/download_file"
      ref: "1.2.1"
    windows:
      repo: "counsyl/windows"
      ref: "0.9.4"
    sys:
      repo: "counsyl/sys"
      ref: "0.9.18"
  repositories:
    concat:
      repo: "https://github.com/mmarod/puppetlabs-concat"
      branch: "add_loglevel"
