---
sudo: required
language: ruby
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
bundler_args: --without rake
matrix:
  fast_finish: true
  include:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 4.0"
before_install:
  - ./.travis.sh
notifications:
  email: false
